### ISSUE TITLE
Use input expressions instead of values

### ISSUE THREAD

**Issue by FlorianPommerening** [FlorianPommerening/FingerJoints#10]
The code currently transforms expressions to values too early. This doesn't make a large difference currently but will be problematic when switching to custom features.

**Comment by it-ony** [comment]
+1 for custom features. I know that the API is still in beta, but I have seen that the DogBone Plugin already is using custom features. I didn't reverse engineer the code, yet, if they're using the beta version of the API. 

What I want to say, is that custom features, would enhance my workflow so dramatically, that I would also go for a beta and of course again contribute.

**Comment by FlorianPommerening** [comment]
I started working on the transformation to custom features a while back. If you want to have a look, you can find the code in the branch `experimental-custom-feature`. It didn't work completely back then and I think they changed the API after I implemented this, so the code in this branch might not work.

Anyway, this issue is not about that but just a small thing that has to be changed first. If you want to help with the transformation to custom features, this issue would be a good start. I think all that needs to be done is to store the expressions of all length fields in `options.py` instead of their values. Then, at the point where they are used, the expressions have to be evaluated. Do you want to give it a go?

**Comment by FlorianPommerening** [comment]
db7be93 should take care of this.
