### ISSUE TITLE
Add option for tolerances

### ISSUE THREAD

**Issue by FlorianPommerening** [FlorianPommerening/FingerJoints#2]
Something that came up in the Fusion forum: it might be useful to have an option for a configurable tolerance between the fingers. This would be a small gap between each two fingers that is cut out of both parts.

**Comment by it-ony** [comment]
+1 for this. I'm using this awesome add-in from you now for building a lot of shelves and boxes for my camper van. Manufacturing this with CNC is a pain in the ass, as its too accurate to manufacture it out of wood and putting the pieces together. 

I might contribute.

**Comment by FlorianPommerening** [comment]
I started implementing this today (https://github.com/FlorianPommerening/FingerJoints/pull/4). Documentation is still missing and the feature is not merged yet. If you would like to test it, you could try running the code on branch `issue2`.

**Comment by it-ony** [comment]
Seems like we worked at the same time at the same feature...
https://github.com/it-ony/FingerJoints/tree/tolerances

**Comment by it-ony** [comment]
Comparing the solution, it's quite similar. But, was nice playing around with the fusion 360 api. Still I'm a little said ;) 
I tested yours, and it works.

**Comment by FlorianPommerening** [comment]
Playing around with the Fusion API was the main motivation behind this plugin for me :smile: 
Sorry you had some duplicated work but good to see that the solutions are similar. I saw that you had some code beautification and a fix to the `stop` method in there as well. If you want to send a pull request for those, I can merge it.

**Comment by FlorianPommerening** [comment]
I pulled some changes from your commits and added a new release (v.1.1) that includes the feature.
