### ISSUE TITLE
feature request: delete all finger joints in one go

### ISSUE THREAD

**Issue by maladon** [FlorianPommerening/FingerJoints#21]
As a designer I understand that finger joints don't re-compute if I change my geometry. I would like to be able to delete all the finger joint history in one go rather than have to select all the proper nodes in history.

I also use the dogbone plugin, and it does that which is super handy. I can delete all the dogbones in one action before changing my model parameters. 

I have a single model file paramaterized so I can make custom drawers. Change the parameters, create finger joints, dobones, and then I use mapboards pro to lay it out for my cnc. Sometimes I've accidentally deleted too much history trying to get the finger joints removes so I can redo them.

**Comment by FlorianPommerening** [comment]
I understand why you would want a feature like this but I still have hope that Autodesk will at some point introduce custom features, which have been in an experimental stage for quite a while. Once they are usable, this problem will go away and joints will just update like other features. What you suggested would be a stop-gap measure we could use until the custom features are usable but given the limited time I can spend on development, I'd rather not spend it on a temporary fix.

I'm sorry, this is probably not what you wanted to hear. I'll close the issue for now but would consider reopening it, if more people ask about something like this. I'll rename the title, so it is easier to find.
