### ISSUE TITLE
Create editable feature

### ISSUE THREAD

**Issue by bringert** [FlorianPommerening/FingerJoints#22]
I haven't looked at the add-ins API and don't know if this is possible to build, but it would be nice if the add-in would produce (ideally a single) editable feature in the timeline. Right now it seems to produce four features (base feature - combine - base feature - combine), and I can't find a way to get back to the original finger joint dialog if I want to change some setting.

**Comment by FlorianPommerening** [comment]
Unfortunately, this is not possible with the current API. Editable features
(called "custom features" in the API) are currently only supported in an
experimental version of the API that wasn't updated for a while. But the hope is
that Autodesk will find a permanent solution eventually and take them out of the
experimental stage. Currently the only way to change parameters is to remove the
features and create a new joint.
