### ISSUE TITLE
Add hole to keep fingerjoint square after routing it in a CNC

### ISSUE THREAD

**Issue by oskarscholander** [FlorianPommerening/FingerJoints#23]
I do not know the correct terms for this feature, but I created some example images.

It would be nice to have the ability to also offset the hole from the corner to optimize the amount of material needed to be removed.

This feature would help manufacturing a lot!

Examples:
![Skärmavbild 2023-02-02 kl  11 33 04](https://user-images.githubusercontent.com/10923809/216301207-ac32a4a8-0390-4382-9527-04860d5dd7ad.png)
![Skärmavbild 2023-02-02 kl  11 35 12](https://user-images.githubusercontent.com/10923809/216301640-6d63aecc-8434-4f96-9f28-b5bbedae87d6.png)

**Comment by FlorianPommerening** [comment]
These holes are called dogbones. There are multiple plugins for creating them, all forking an original version and modifying it in some way, for example https://github.com/DVE2000/Dogbone/
I don't plan to add this functionality here as well, as it doesn't fit with how the code is designed (I do not require pieces to be flat pieces meeting at 90 degree angles).
