### ISSUE TITLE
Suggestion: Cutouts for CNC toolpath (Dogbones)

### ISSUE THREAD

**Issue by andrewwong2000** [FlorianPommerening/FingerJoints#5]
The plugin works great and thanks so much ! 

One suggestion is to add cutouts on inside corners so a CNC machine can machine the finger joints.

eg. Allow input of tool diameter in mm/in, then on the inside corners radius the inner corner.

**Comment by FlorianPommerening** [comment]
Thanks for the suggestion. Unfortunately, this is not easy to add as the code currently doesn't reason about the join on that level (it doesn't know about corners). Computing dogbones is easier if you know that the parts are rectangular boards that meet at 90 degree angles and do not overlap but the plugin doesn't make any assumptions about this. The join could be between two round parts that pass through each other at multiple points and angles. It would be tricky to even specify what exactly the dogbone should look like in general. I don't have any plans to add this functionality at the moment.

As a workaround I can recommend first creating the joins and then creating the dogbones afterwards with this plugin: https://github.com/DVE2000/Dogbone/
